import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from 'jspdf';
import * as htmlToImage from 'html-to-image';
import { 
  Brain, 
  Trash2, 
  Calendar, 
  Search, 
  Copy, 
  Check, 
  Loader2,
  FileText,
  AlertCircle
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { cn } from '@/utils/cn';
import { formatDate } from '@/utils/formatDate';
import api from '@/services/api';

const Notes = () => {
  const [notes, setNotes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [copiedId, setCopiedId] = useState(null);
  const [exportingId, setExportingId] = useState(null);
  const noteRefs = useRef({});

  const downloadSinglePDF = async (noteId, noteTitle) => {
    const element = noteRefs.current[noteId];
    if (!element) {
      console.error("PDF Export Error: Note element not found");
      alert("Error: Note element not found.");
      return;
    }
    
    setExportingId(noteId);
    try {
      const filter = (node) => node?.dataset?.html2canvasIgnore !== 'true';

      const imgData = await htmlToImage.toPng(element, { 
        pixelRatio: 2, 
        backgroundColor: document.documentElement.classList.contains('dark') ? '#111827' : '#ffffff',
        filter: filter
      });
      
      const pdfWidth = 210; // Standard A4 width in mm
      const pdfHeight = (element.offsetHeight * pdfWidth) / element.offsetWidth;
      
      // Create a single continuous page that perfectly fits the note (padding included)
      const totalPageHeight = pdfHeight + 40; 
      
      const pdf = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: [pdfWidth, totalPageHeight]
      });
      
      // Header
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.setTextColor(168, 85, 247); // purple-500
      pdf.text("AI for Lazy Genius", pdfWidth / 2, 12, { align: "center" });

      // Note Content Image
      pdf.addImage(imgData, 'PNG', 0, 20, pdfWidth, pdfHeight);
      
      // Footer
      pdf.setFont("helvetica", "italic");
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      const dateStr = new Date().toLocaleString();
      pdf.text(`Generated by Lazy Genius AI - ${dateStr}`, pdfWidth / 2, totalPageHeight - 10, { align: "center" });
      
      pdf.save(`${noteTitle.replace(/[^a-zA-Z0-9]/g, '-')}-Notes.pdf`);
    } catch (err) {
      console.error("Failed to generate PDF", err);
      alert("Failed to generate PDF: " + err.message);
    } finally {
      setExportingId(null);
    }
  };

  useEffect(() => {
    fetchNotes();
  }, []);

  const fetchNotes = async () => {
    try {
      const { data } = await api.get('/notes');
      setNotes(data);
    } catch (err) {
      console.error("Failed to fetch notes:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this note?")) {
      try {
        await api.delete(`/notes/${id}`);
        setNotes(notes.filter(n => n._id !== id));
      } catch (err) {
        console.error("Delete failed:", err);
      }
    }
  };

  const copyNote = (id, content) => {
    navigator.clipboard.writeText(content);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const filteredNotes = notes.filter(n => 
    n.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    n.originalText.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) return <LoadingState />;

  return (
    <div className="min-h-screen pt-0 pb-12 px-4">
      <div className="max-w-6xl mx-auto">
        {/* Premium Header */}
        <header className="relative py-8 sm:py-12 px-6 sm:px-10 lg:px-12 bg-gradient-to-br from-purple-50 via-white to-fuchsia-50 dark:from-[#111827] dark:via-[#111827] dark:to-purple-900/10 rounded-[32px] mb-8 sm:mb-16 overflow-hidden shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-purple-100 dark:border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-8 z-10">
          
          <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-purple-400/20 dark:bg-purple-600/20 rounded-full blur-[100px] translate-x-1/3 -translate-y-1/3 pointer-events-none" />

          <div className="relative z-10 space-y-3">
            <h1 className="text-3xl sm:text-5xl lg:text-[56px] font-black text-slate-900 dark:text-white tracking-tight leading-[1.1] text-center md:text-left">
              My <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-600 via-fuchsia-500 to-purple-600 animate-gradient bg-[length:200%_auto] drop-shadow-sm">Brain Bank</span>
            </h1>
            <p className="text-slate-500 dark:text-slate-400 font-black uppercase tracking-widest text-[10px] md:text-xs text-center md:text-left">
              All your AI-distilled knowledge in one place
            </p>
          </div>

          <div className="relative group z-10 w-full md:w-auto flex-grow max-w-sm">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-purple-600 transition-colors" size={20} />
            <input 
              type="text" 
              placeholder="Search your notes..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-12 pr-6 py-4 bg-white/80 dark:bg-[#111827]/80 backdrop-blur-md border border-slate-200 dark:border-white/10 rounded-2xl w-full shadow-sm focus:ring-2 focus:ring-purple-500 outline-none transition-all hover:border-purple-200 dark:hover:border-purple-500/30 text-slate-900 dark:text-white placeholder:text-slate-400 font-medium"
            />
          </div>
        </header>

        {/* Content */}
        {filteredNotes.length === 0 ? (
          <EmptyState searchTerm={searchTerm} />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <AnimatePresence mode="popLayout">
              {filteredNotes.map((note) => (
                <motion.div
                  key={note._id}
                  ref={(el) => noteRefs.current[note._id] = el}
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  className="bg-white dark:bg-[#111827] rounded-[32px] border border-slate-200/80 dark:border-white/5 p-5 sm:p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-none group hover:-translate-y-2 hover:shadow-[0_20px_40px_rgb(168,85,247,0.15)] hover:border-purple-300 dark:hover:border-purple-500/40 transition-all duration-500 relative overflow-hidden"
                >
                  {/* Subtle Gradient Glow */}
                  <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" data-html2canvas-ignore="true" />
                  
                  <div className="relative z-10 flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-6">
                    <div className="space-y-1.5">
                      <h3 className="text-xl font-black text-slate-900 dark:text-white leading-tight group-hover:text-purple-600 transition-colors">
                        {note.title}
                      </h3>
                      <div className="flex items-center gap-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                        <Calendar size={12} />
                        <span>{formatDate(note.createdAt)}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 transition-all duration-300 flex-shrink-0" data-html2canvas-ignore="true">
                      <button 
                        onClick={() => downloadSinglePDF(note._id, note.title)}
                        disabled={exportingId === note._id}
                        className="h-10 flex items-center gap-1.5 px-4 rounded-xl bg-gradient-to-r from-purple-600 to-fuchsia-500 text-white hover:from-purple-500 hover:to-fuchsia-400 shadow-[0_0_15px_rgba(168,85,247,0.4)] hover:shadow-[0_0_25px_rgba(168,85,247,0.6)] transition-all text-[11px] font-black uppercase tracking-wider disabled:opacity-70 disabled:cursor-not-allowed whitespace-nowrap"
                      >
                        {exportingId === note._id ? (
                          <>
                            <Loader2 size={14} className="animate-spin" />
                            <span>Exporting...</span>
                          </>
                        ) : (
                          <>
                            <FileText size={14} />
                            <span>Export PDF</span>
                          </>
                        )}
                      </button>
                      <button 
                        onClick={() => copyNote(note._id, note.aiNotes)}
                        className="h-10 w-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-white/5 text-slate-400 hover:bg-purple-50 dark:hover:bg-purple-500/20 hover:text-purple-600 transition-all"
                        title="Copy to clipboard"
                      >
                        {copiedId === note._id ? <Check size={18} /> : <Copy size={18} />}
                      </button>
                      <button 
                        onClick={() => handleDelete(note._id)}
                        className="h-10 w-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-white/5 text-slate-400 hover:bg-rose-50 dark:hover:bg-rose-500/20 hover:text-rose-500 transition-all"
                        title="Delete note"
                      >
                        <Trash2 size={18} />
                      </button>
                    </div>
                  </div>

                  <div className="relative z-10 space-y-6">
                    <div className="p-4 sm:p-5 bg-slate-50 dark:bg-white/5 rounded-2xl border-l-4 border-purple-500">
                      <p className="text-sm text-slate-500 dark:text-slate-400 italic line-clamp-2 leading-relaxed">
                        "{note.originalText}"
                      </p>
                    </div>

                    <div className="prose prose-slate dark:prose-invert max-w-none 
                      prose-p:text-sm prose-p:text-slate-600 dark:prose-p:text-slate-400 prose-p:leading-relaxed
                      prose-h2:text-lg prose-h2:font-black prose-h2:mt-6 prose-h2:mb-3 prose-h2:text-purple-600 dark:prose-h2:text-purple-400
                      prose-li:text-sm prose-li:text-slate-600 dark:prose-li:text-slate-400
                    ">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {note.aiNotes}
                      </ReactMarkdown>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </div>
    </div>
  );
};

const LoadingState = () => (
  <div className="min-h-screen flex flex-col items-center justify-center gap-4">
    <Loader2 className="w-12 h-12 text-indigo-600 animate-spin" />
    <p className="text-xs font-black text-zinc-400 uppercase tracking-widest animate-pulse">Syncing Brain Bank...</p>
  </div>
);

const EmptyState = ({ searchTerm }) => (
  <div className="py-32 flex flex-col items-center justify-center text-center">
    <div className="p-6 bg-slate-50 dark:bg-[#111827] border border-slate-100 dark:border-white/5 shadow-sm rounded-[40px] mb-8 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-purple-500/10 to-transparent opacity-50" />
      {searchTerm ? <AlertCircle className="w-16 h-16 text-slate-300 relative z-10" /> : <Brain className="w-16 h-16 text-purple-400 relative z-10" />}
    </div>
    <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-2 tracking-tight">
      {searchTerm ? "No notes found matching your search" : "Your Brain Bank is empty"}
    </h2>
    <p className="text-slate-500 text-sm max-w-xs font-medium">
      {searchTerm ? "Try searching for a different keyword." : "Highlight text in any article and save it to see your notes here!"}
    </p>
  </div>
);

export default Notes;
